#!/usr/bin/sh

export DISPLAY=:0
export XAUTHORITY=/home/srsantos/.Xauthority
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

state=$8
xserver=$( pidof Xorg )

if [ "$state" = "NOCARD" ] && [ ${#xserver} -gt 0 ]; then
     /usr/bin/pkill -9 dunst && /usr/bin/xset dpms force off && /usr/bin/gpgconf --kill gpg-agent
elif [ "$state" = "NOCARD" ] && [ -z $xserver ]; then
     /usr/bin/physlock -d -s
else
     exit 0
fi

